# **IBM Telco Customer Churn Dataset — Data Cleaning & Preprocessing**

## **Project Overview**
This project analyzes customer churn behavior using the IBM Telco Customer Churn dataset.

The goal of this phase is to clean and preprocess the raw dataset before performing exploratory data analysis (EDA).

This notebook includes:
- Loading the dataset
- Inspecting data quality
- Handling missing values
- Fixing incorrect data types
- Removing inconsistencies
- Dropping unnecessary columns
- Adding new columns
- Exporting the cleaned dataset

## **File upload**

In [ ]:
#file upload cell for Colab environment only.
from google.colab import files
uploaded = files.upload()

Saving Telco_customer_churn.xlsx to Telco_customer_churn.xlsx

## **Loading Data**

In [ ]:
#importing libraries
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_excel('/content/Telco_customer_churn.xlsx')

## **Checking**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

We can see that the Total Charges is object datatype. Let's keep that in mind.

In [ ]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [ ]:
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [ ]:
#checking to see if there are any white spaces instead of null
df.select_dtypes(include='object').apply(lambda x: x.str.isspace().sum())

CustomerID            0
Country               0
State                 0
City                  0
Lat Long              0
Gender                0
Senior Citizen        0
Partner               0
Dependents            0
Phone Service         0
Multiple Lines        0
Internet Service      0
Online Security       0
Online Backup         0
Device Protection     0
Tech Support          0
Streaming TV          0
Streaming Movies      0
Contract              0
Paperless Billing     0
Payment Method        0
Total Charges        11
Churn Label           0
Churn Reason          0
dtype: int64

In [ ]:
# wow! total charges has disguised null values. what should i do now hmm?
df.replace(r'^\s+$', np.nan, regex=True, inplace=True)

In [ ]:
#check for null values again
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges          11
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [ ]:
# since only 11 rows are null, i will just drop them
df.dropna(subset=['Total Charges'], inplace=True)

In [ ]:
df.shape #to see if it's all good and it is yay

(7032, 33)

In [ ]:
df.dtypes

CustomerID            object
Count                  int64
Country               object
State                 object
City                  object
Zip Code               int64
Lat Long              object
Latitude             float64
Longitude            float64
Gender                object
Senior Citizen        object
Partner               object
Dependents            object
Tenure Months          int64
Phone Service         object
Multiple Lines        object
Internet Service      object
Online Security       object
Online Backup         object
Device Protection     object
Tech Support          object
Streaming TV          object
Streaming Movies      object
Contract              object
Paperless Billing     object
Payment Method        object
Monthly Charges      float64
Total Charges        float64
Churn Label           object
Churn Value            int64
Churn Score            int64
CLTV                   int64
Churn Reason          object
dtype: object

Total charges is now float data type, as it should be.

## **Dropping Columns**

In [ ]:
df.columns #checking columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='object')

do not need all these for churn analysis. like what am i going to do with customer id? and since i am not doing geographical analysis, dont need the location either. the count is also useless. why is there even a churn label when there is a churn value? Churn score and CLTV are not raw data either. dropping all these. yay less columns!

In [ ]:
df = df.drop(columns=[
    'CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code','Lat Long',
    'Latitude', 'Longitude', 'Churn Label', 'Churn Score', 'CLTV'])

## **Adding Columns**

In [ ]:
df.describe() #looking at the values before setting them to different classes

       Tenure Months  Monthly Charges  Total Charges  Churn Value
count    7032.000000      7032.000000    7032.000000  7032.000000
mean       32.421786        64.798208    2283.300441     0.265785
std        24.545260        30.085974    2266.771362     0.441782
min         1.000000        18.250000      18.800000     0.000000
25%         9.000000        35.587500     401.450000     0.000000
50%        29.000000        70.350000    1397.475000     0.000000
75%        55.000000        89.862500    3794.737500     1.000000
max        72.000000       118.750000    8684.800000     1.000000

Adding tenure groups column

In [ ]:
df.insert(df.columns.get_loc('Tenure Months') + 1, 'Tenure Groups',
          pd.cut(df['Tenure Months'], bins=[0,12,24,36,48,60,72],
                 labels=['0-12','13-24','25-36','37-48','49-60','61-72'],
                 include_lowest=True))

Adding charge category column

In [ ]:
df.insert(df.columns.get_loc('Monthly Charges') + 1, 'Charge Category',
          pd.cut(df['Monthly Charges'], bins=[18,50,85,120],
                 labels=['Low','Medium','High'],
                 include_lowest=True))

Adding a column to see clearly how many services each customer is subscribed to

In [ ]:
cols = ['Phone Service', 'Multiple Lines', 'Internet Service',
        'Online Security', 'Online Backup', 'Device Protection',
        'Tech Support', 'Streaming TV', 'Streaming Movies']

for col in cols:
    print(f"{col}: {df[col].unique()}") #checking the unique values of these columns

Phone Service: ['Yes' 'No']
Multiple Lines: ['No' 'Yes' 'No phone service']
Internet Service: ['DSL' 'Fiber optic' 'No']
Online Security: ['Yes' 'No' 'No internet service']
Online Backup: ['Yes' 'No' 'No internet service']
Device Protection: ['No' 'Yes' 'No internet service']
Tech Support: ['No' 'Yes' 'No internet service']
Streaming TV: ['No' 'Yes' 'No internet service']
Streaming Movies: ['No' 'Yes' 'No internet service']

we can see that there is no 'Yes' for internet service. so we need to count that separately.

In [ ]:
service_cols = ['Phone Service', 'Multiple Lines', 'Online Security',
                'Online Backup', 'Device Protection',
                'Tech Support', 'Streaming TV', 'Streaming Movies']

service_count = (df[service_cols] == 'Yes').sum(axis=1) + df['Internet Service'].isin(['DSL', 'Fiber optic']).astype(int)

df.insert(df.columns.get_loc('Streaming Movies') + 1, 'Service Count', service_count)

In [ ]:
df.head()

,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Tenure Groups,Phone Service,Multiple Lines,Internet Service,Online Security,...,Streaming Movies,Service Count,Contract,Paperless Billing,Payment Method,Monthly Charges,Charge Category,Total Charges,Churn Value,Churn Reason
0,Male,No,No,No,2,0-12,Yes,No,DSL,Yes,...,No,4,Month-to-month,Yes,Mailed check,53.85,Medium,108.15,1,Competitor made better offer
1,Female,No,No,Yes,2,0-12,Yes,No,Fiber optic,No,...,No,2,Month-to-month,Yes,Electronic check,70.70,Medium,151.65,1,Moved
2,Female,No,No,Yes,8,0-12,Yes,Yes,Fiber optic,No,...,Yes,6,Month-to-month,Yes,Electronic check,99.65,High,820.50,1,Moved
3,Female,No,Yes,Yes,28,25-36,Yes,Yes,Fiber optic,No,...,Yes,7,Month-to-month,Yes,Electronic check,104.80,High,3046.05,1,Moved
4,Male,No,No,Yes,49,49-60,Yes,Yes,Fiber optic,No,...,Yes,7,Month-to-month,Yes,Bank transfer (automatic),103.70,High,5036.30,1,Competitor had better devices

In [ ]:
df.columns

Index(['Gender', 'Senior Citizen', 'Partner', 'Dependents', 'Tenure Months',
       'Tenure Groups', 'Phone Service', 'Multiple Lines', 'Internet Service',
       'Online Security', 'Online Backup', 'Device Protection', 'Tech Support',
       'Streaming TV', 'Streaming Movies', 'Service Count', 'Contract',
       'Paperless Billing', 'Payment Method', 'Monthly Charges',
       'Charge Category', 'Total Charges', 'Churn Value', 'Churn Reason'],
      dtype='object')

In [ ]:
df.shape

(7032, 24)

Looks good for now.

## **Exporting Cleaned CSV**

In [ ]:
df.to_csv('telco_churn_cleaned.csv', index=False)

In [ ]:
# Downloadinging from Colab
from google.colab import files
files.download('telco_churn_cleaned.csv')

## **Conclusion**

In this phase, the IBM Telco Customer Churn dataset was successfully cleaned and preprocessed for further analysis.


The cleaned dataset is now ready for Phase 2: Exploratory Data Analysis (EDA).